name = "reino-nas-ruas"
compatibility_date = "2025-07-24"
main = ".vercel/output/static/_worker.js"
keep_vars = true

[site]
bucket = ".vercel/output/static"

[build]
command = "npm run build"

[env.production]
name = "reino-nas-ruas"
routes = ["reinonasruas.org.br/*", "www.reinonasruas.org.br/*"]

[env.production.vars]
DIRECTUS_URL = "http://52.87.164.16:8050"
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://reinonasruas.org.br"
NEXT_PUBLIC_API_TIMEOUT = "30000"
NEXT_PUBLIC_MAX_RETRIES = "5"
NEXT_PUBLIC_CACHE_DURATION = "600"
NEXT_PUBLIC_REVALIDATE_DURATION = "7200"
NEXT_PUBLIC_ALLOWED_ORIGINS = "https://reinonasruas.org.br,https://www.reinonasruas.org.br"
NEXT_PUBLIC_IMAGE_QUALITY = "90"
NEXT_PUBLIC_IMAGE_FORMAT = "webp"
NEXT_PUBLIC_DEBUG = "false"
LOG_LEVEL = "error"