name = 'reino-nas-ruas'
compatibility_date = "2025-07-24"
main = ".vercel/output/static/_worker.js"

[site]
bucket = ".vercel/output/static"

[build]
command = "npm run build"

[env.production]
name = "reino-nas-ruas"
routes = [
  "reinonasruas.org.br/*",
  "www.reinonasruas.org.br/*"
]